### ISSUE TITLE
LDpred2 issue with MoBa data(?)

### ISSUE THREAD

**Issue by espenhgn** [comorment/containers#124]
**Describe the bug**
The versions of the `ldpred2.R` and `createBackingFile.R` scripts from the main branch to a MoBa sample/height phenotype, the predicted scores do not correlate with the phenotype values. Could be a user error though.

@deepchocolate, @ofrei, do you see any obvious issues below?

**To Reproduce**
Commands:
```
export MOBA="/cluster/projects/p697/users/ofrei/2022_moba_height_traj"
export SINGULARITY_BIND="/ess/p697/data/durable/users/espehage/comorment/ldpred2_ref:/ldpred2_ref,/cluster/projects/p697/users/ofrei/2022_moba_height_traj:/MOBA"
export RSCRIPT="singularity exec --home=/ess/p697/data/durable/users/espehage/comorment/containers-fix-17/pgs:/home /ess/p697/data/durable/users/espehage/comorment/containers-fix-17/singularity/r.sif Rscript"
$RSCRIPT Rscripts/createBackingFile.R /MOBA/MoBaPsychGen_v1-500kSNPs-child.bed MoBaPsychGen_v1-500kSNPs-child.rds
$RSCRIPT Rscripts/ldpred2.R --ldpred-mode inf --file-pheno /MOBA/master_file.csv --geno-file MoBaPsychGen_v1-500kSNPs-child.rds --sumstats /MOBA/out/run10_regenie_height_8y_rint.gz --out results/PGS_MoBa_LDpred2_inf/test.score  --cores 16 --col-pheno height_8y_rint

```
Log file (i see creating the .rds file step is bypassed here but shouldn't matter):
```
File MoBaPsychGen_v1-500kSNPs-child.rds already exists. Exiting.
Loading backingfile: MoBaPsychGen_v1-500kSNPs-child.rds 
Loading external phenotype in file /MOBA/master_file.csv 

### Reading LD reference meta-file from  /ldpred2_ref/map_hm3_plus.rds 

### Reading summary statistics /MOBA/out/run10_regenie_height_8y_rint.gz 
Loaded 6981748 SNPs
Filtering SNPs based on --chr2use
Retained 6981748 out of 6981748 
Matching sumstats to genotypes
Matching sumstats to LD reference

### Loading LD reference from  /ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr@.rds 
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr1.rds : loading LD for 27082 out of 117534 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr2.rds : loading LD for 27928 out of 120469 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr3.rds : loading LD for 22692 out of 100666 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr4.rds : loading LD for 19735 out of 94010 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr5.rds : loading LD for 19883 out of 91117 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr6.rds : loading LD for 25139 out of 94264 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr7.rds : loading LD for 18207 out of 81254 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr8.rds : loading LD for 18182 out of 78428 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr9.rds : loading LD for 14914 out of 65806 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr10.rds : loading LD for 17939 out of 75354 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr11.rds : loading LD for 17792 out of 72406 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr12.rds : loading LD for 16462 out of 70201 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr13.rds : loading LD for 12588 out of 53449 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr14.rds : loading LD for 11027 out of 47714 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr15.rds : loading LD for 9744 out of 43091 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr16.rds : loading LD for 9881 out of 46228 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr17.rds : loading LD for 8598 out of 40436 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr18.rds : loading LD for 9468 out of 42976 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr19.rds : loading LD for 6507 out of 30552 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr20.rds : loading LD for 8089 out of 36426 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr21.rds : loading LD for 4528 out of 20582 SNPs
/ldpred2_ref/ldref_hm3_plus/LD_with_blocks_chr22.rds : loading LD for 4422 out of 21233 SNPs

### Running LD score regression
Results: Intercept = 1.004769 H2 = 0.6818907 

### Starting polygenic scoring
Running LDPRED2 infinitesimal model
Calculating beta inf
Imputing missing genotypes...
Scoring all individuals...
Correlation with phenotype: 0.0056 

### Writing fam file with PGS and phenotype
```
So the reported correlation is practically nil. This should not be the case as PRSice2 results in a clear dependency between phenotype and PRS score (see below)

**Screenshots**
LDpred2-infinitesimal:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/2492641/217240487-e23dba0e-85e0-49dd-8c17-f153fd53a09e.png">

vs. PRSice2:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/2492641/217240336-924a7a2c-1aa4-42d9-a97d-c1b4adbb9d60.png">

**Setup (please complete the following information - if applicable):**
 - Singularity version : apptainer 1.1.5-1el7
 - Container file and version: [`r.sif` from branch fix-17](https://github.com/comorment/containers/blob/fix-17/singularity/r.sif)

**Additional context**

**Comment by deepchocolate** [comment]
Quite strange that the LDpred score ranges all the way from -2 to 2, almost like as it just generated a random normal distribution.
I haven't tried reading compressed sumstats .gz files directly, it's not something weird going on there?

**Comment by espenhgn** [comment]
I'll test with the uncompressed sumstats file. Didn't look into the definition of this fread2 function earlier, but it appears to expect text files.

**Comment by espenhgn** [comment]
@deepchocolate, I ruled out that reading sumstats on .gz format is the issue. Same result, as `bigreadr::fread2` can deal with it:
```
> df <- fread2('/REF/examples/prsice2/Height.gwas.txt.gz')
> df[1:2, 1:11]
  CHR     BP        SNP A1 A2      N         SE        P        OR      INFO
1   1 756604  rs3131962  A  G 388028 0.00301666 0.483171 0.9978869 0.8905579
2   1 768448 rs12562034  A  G 388028 0.00329472 0.834808 1.0006873 0.8958935
        MAF
1 0.3693896
2 0.3368458
```

 I'll add the corresponding PRSice commands I've called, shortly.

**Comment by espenhgn** [comment]
Hi. The sumstats example I posted does indeed not contain BETA (just showcasing that `bigreadr::fread2` can read a compressed CSV like file). The `run10_regenie_height_8y_rint.gz` file from @ofrei's working dir/MOBA on TSD does though:
![image](https://user-images.githubusercontent.com/2492641/217553298-9c5d4aa3-7ad5-465e-b8f0-7e5df3f0d525.png)
As far as I can tell, the defaults for dealing with the sumstats in the `ldpred2.R` script (`--col-stat` etc.) is set appropriately for this file.
 
For reference, here's how I did the PRSice2 calculations:
```
export SIF=/ess/p697/data/durable/users/espehage/comorment/containers-fix-17/singularity
export REFERENCE=/ess/p697/data/durable/users/espehage/comorment/containers-fix-17/reference
export LDPRED2_REF=/ess/p697/data/durable/users/espehage/comorment/ldpred2_ref
export MOBA=/cluster/projects/p697/users/ofrei/2022_moba_height_traj
export SUMSTATS=/cluster/projects/p697/projects/SUMSTATv2
export SINGULARITY_BIND=$REFERENCE:/REF,$LDPRED2_REF:/ldpred2_ref,$MOBA:/MOBA,$SUMSTATS:/SUMSTATS
export RSCRIPT="singularity exec --home=/ess/p697/data/durable/users/espehage/comorment/containers-fix-17/pgs:/home $SIF/r.sif Rscript"

# extract phenotype column
$RSCRIPT Rscripts/extract_columns.R --input-file /MOBA/master_file.csv --columns FID IID height_8y_rint --output-file results/PGS_MoBa_prsice2/MoBaPsychGen_v1-500kSNPs-child.height_8y_rint --header T --na NA --sep " "
# extract covariates (SEX, PC1-6)
$RSCRIPT Rscripts/extract_columns.R --input-file /MOBA/master_file.csv --columns FID IID SEX PC1 PC2 PC3 PC4 PC5 PC6 --output-file results/PGS_MoBa_prsice2/MoBaPsychGen_v1-500kSNPs-child.covariate --header T --na NA --sep " "
$RSCRIPT Rscripts/PRSice.R --prsice /usr/bin/PRSice_linux --base /MOBA/out/run10_regenie_height_8y_rint.gz --target /MOBA/MoBaPsychGen_v1-500kSNPs-child --binary-target F --pheno results/PGS_MoBa_prsice2/MoBaPsychGen_v1-500kSNPs-child.height_8y_rint --cov results/PGS_MoBa_prsice2/MoBaPsychGen_v1-500kSNPs-child.covariate --base-maf MAF:0.01 --base-info INFO:0.8 --out results/PGS_MoBa_prsice2/MoBaPsychGen_v1-500kSNPs-child --thread 16 --pheno-col height_8y_rint --pvalue P
```
log:
```
INFO:    Environment variable SINGULARITY_BIND is set, but APPTAINER_BIND is preferred
INFO:    Environment variable SINGULARITY_BIND is set, but APPTAINER_BIND is preferred
INFO:    Environment variable SINGULARITY_BIND is set, but APPTAINER_BIND is preferred
PRSice 2.3.3 (2020-08-05) 
https://github.com/choishingwan/PRSice
(C) 2016-2020 Shing Wan (Sam) Choi and Paul F. O'Reilly
GNU General Public License v3
If you use PRSice in any published work, please cite:
Choi SW, O'Reilly PF.
PRSice-2: Polygenic Risk Score Software for Biobank-Scale Data.
GigaScience 8, no. 7 (July 1, 2019)
2023-02-08 14:03:39
/usr/bin/PRSice_linux \
    --a1 A1 \
    --a2 A2 \
    --bar-levels 0.001,0.05,0.1,0.2,0.3,0.4,0.5,1 \
    --base /MOBA/out/run10_regenie_height_8y_rint.gz \
    --base-info INFO:0.8 \
    --base-maf MAF:0.01 \
    --binary-target F \
    --bp BP \
    --chr CHR \
    --clump-kb 250kb \
    --clump-p 1.000000 \
    --clump-r2 0.100000 \
    --cov results/PGS_MoBa_prsice2/MoBaPsychGen_v1-500kSNPs-child.covariate \
    --interval 5e-05 \
    --lower 5e-08 \
    --num-auto 22 \
    --out results/PGS_MoBa_prsice2/MoBaPsychGen_v1-500kSNPs-child \
    --pheno results/PGS_MoBa_prsice2/MoBaPsychGen_v1-500kSNPs-child.height_8y_rint \
    --pheno-col height_8y_rint \
    --pvalue P \
    --seed 3025619174 \
    --snp SNP \
    --stat BETA \
    --target /MOBA/MoBaPsychGen_v1-500kSNPs-child \
    --thread 16 \
    --upper 0.5

Warning: INFO field not found in base file, will ignore 
         INFO filtering 
Warning: MAF field not found in base file. Will not perform 
         MAF filtering on the base file 

Initializing Genotype file: 
/MOBA/MoBaPsychGen_v1-500kSNPs-child (bed) 

Start processing run10_regenie_height_8y_rint 
================================================== 

Base file: /MOBA/out/run10_regenie_height_8y_rint.gz 
GZ file detected. Header of file is: 
SNP     CHR     BP      A1      A2      N       FRQ     Z       BETA    SE      P 

Reading 100.00%
6981748 variant(s) observed in base file, with: 
1061409 ambiguous variant(s) excluded 
5920339 total variant(s) included from base file 

Loading Genotype info from target 
================================================== 

76577 people (38935 male(s), 37195 female(s)) observed 
76577 founder(s) included 

1493 variant(s) not found in previous data 
498750 variant(s) included 

Phenotype file: 
results/PGS_MoBa_prsice2/MoBaPsychGen_v1-500kSNPs-child.height_8y_rint 
Column Name of Sample ID: FID+IID 
Note: If the phenotype file does not contain a header, the 
column name will be displayed as the Sample ID which is 
expected. 

There are a total of 1 phenotype to process 

Start performing clumping 

Clumping Progress: 100.00%
Number of variant(s) after clumping : 72885 

Processing the 1 th phenotype 

height_8y_rint is a continuous phenotype 
62 sample(s) without phenotype 
28482 sample(s) with valid phenotype 

Processing the covariate file: 
results/PGS_MoBa_prsice2/MoBaPsychGen_v1-500kSNPs-child.covariate 
============================== 

Include Covariates: 
Name    Missing Number of levels 
SEX     0       - 
PC1     0       - 
PC2     0       - 
PC3     0       - 
PC4     0       - 
PC5     0       - 
PC6     0       - 

After reading the covariate file, 28482 sample(s) included 
in the analysis 


Start Processing
Processing 100.00%
There are 1 region(s) with p-value less than 1e-5. Please 
note that these results are inflated due to the overfitting 
inherent in finding the best-fit PRS (but it's still best 
to find the best-fit PRS!). 
You can use the --perm option (see manual) to calculate an 
empirical P-value. 

Begin plotting
Current Rscript version = 2.3.3
Plotting Bar Plot
Plotting the high resolution plot
```

**Comment by deepchocolate** [comment]
Ok, great! I tested with a binary phenotype (depression diagnosis) that I worked with using prsice, and those results are similar to prior versions of the LDpred2.R script and prsice... Strange...

**Comment by espenhgn** [comment]
Yes, quite strange indeed. I had set up a comparison between plink, prsice, ldpred2 (inf/auto) on the demo /REF/example/prsice2/*  dataset (also height) in https://github.com/comorment/containers/blob/fix-17/pgs/run_pgs_w_QC.py, which produce results that are comparable (at least in terms of trends):
![image](https://user-images.githubusercontent.com/2492641/217789003-ee45d9ad-af7d-4fe0-a34b-87618dabef71.png)

**Comment by ofrei** [comment]
@espenhgn could you try with UKB Height GWAS ?
<img width="770" alt="image" src="https://user-images.githubusercontent.com/13171449/218748366-3f60ca93-994f-4701-affe-c5a6010d744d.png">

**Comment by ofrei** [comment]
Or the following one: 
<img width="279" alt="image" src="https://user-images.githubusercontent.com/13171449/218748614-986888f5-89c3-4d4d-ad93-5fcce48d0581.png">

**Comment by ofrei** [comment]
Another idea could be to test out in UK Biobank
https://wiki.norment.uiocloud.no/doku.php?id=uk_biobank
This should be available in TSD. Phenotypes (e.g. height) can be taken from 
/cluster/projects/p33/s3-api/ukblake/phenotypes
and slightly processed genotypes from here
/cluster/projects/p33/s3-api/ukbdata/projects/plsa_mixer/ukb_genetics_qc

**Comment by ofrei** [comment]
https://github.com/precimed/ukb ukb_helper.py

**Comment by deepchocolate** [comment]
Btw, way doesn't the log file show any result from the matching? Did you remove it?
```
### Reading summary statistics /MOBA/out/run10_regenie_height_8y_rint.gz 
Loaded 6981748 SNPs
Filtering SNPs based on --chr2use
Retained 6981748 out of 6981748 
Matching sumstats to genotypes
Matching sumstats to LD reference
```

**Comment by deepchocolate** [comment]
@espenhgn @ofrei I've found a problem..  I looked closer at the output of my test script and noted that there were a lot more reversed alleles than in the tutorial.

Looking at the tutorial the "map" object (corresponding to the .bim file) looks like this
```
##   ..$ chromosome  : int [1:45337] 1 1 1 1 1 1 1 1 1 1 ...
##   ..$ marker.ID   : chr [1:45337] "rs3934834" "rs12726255" "rs11260549" "..
##   ..$ genetic.dist: num [1:45337] 0.359 0.408 0.932 0.986 1.107 ...
##   ..$ physical.pos: int [1:45337] 1005806 1049950 1121794 1162435 1314015..
##   ..$ allele1     : chr [1:45337] "T" "G" "A" "A" ...
##   ..$ allele2     : chr [1:45337] "C" "A" "G" "C" ...
```
In the tutorial they rename the columns like this (also removing one):
```
map <- setNames(obj.bigSNP$map[-3], c("chr", "rsid", "pos", "a1", "a0"))
```
Meaning that allele1=a1 and allele2=a0
Looking at `ldpred2.R` this is performed at:
https://github.com/comorment/containers/blob/b984ff66f13d4d16a2ab4ee4f2c32f3edd304bd5/usecases/LDpred2/ldpred2.R#L129-L131

If I interpet this correct, since all are reversed in the map, those that are as expected in the sumstats get an inverted effect

**Comment by espenhgn** [comment]
> Btw, way doesn't the log file show any result from the matching? Did you remove it?
> 
> ```
> ### Reading summary statistics /MOBA/out/run10_regenie_height_8y_rint.gz 
> Loaded 6981748 SNPs
> Filtering SNPs based on --chr2use
> Retained 6981748 out of 6981748 
> Matching sumstats to genotypes
> Matching sumstats to LD reference
> ```

What I posted above should be the full STDOUT from the calls to `ldpred2.R`, captured with the `tee` utility. My invocation would be something like `bash commands.sh | tee logfile.txt`. I don't think I removed something.

**Comment by espenhgn** [comment]
> @espenhgn @ofrei I've found a problem.. I looked closer at the output of my test script and noted that there were a lot more reversed alleles than in the tutorial.
> 
> Looking at the tutorial the "map" object (corresponding to the .bim file) looks like this
> 
> ```
> ##   ..$ chromosome  : int [1:45337] 1 1 1 1 1 1 1 1 1 1 ...
> ##   ..$ marker.ID   : chr [1:45337] "rs3934834" "rs12726255" "rs11260549" "..
> ##   ..$ genetic.dist: num [1:45337] 0.359 0.408 0.932 0.986 1.107 ...
> ##   ..$ physical.pos: int [1:45337] 1005806 1049950 1121794 1162435 1314015..
> ##   ..$ allele1     : chr [1:45337] "T" "G" "A" "A" ...
> ##   ..$ allele2     : chr [1:45337] "C" "A" "G" "C" ...
> ```
> 
> In the tutorial they rename the columns like this (also removing one):
> 
> ```
> map <- setNames(obj.bigSNP$map[-3], c("chr", "rsid", "pos", "a1", "a0"))
> ```
> 
> Meaning that allele1=a1 and allele2=a0 Looking at `ldpred2.R` this is performed at:
> 
> https://github.com/comorment/containers/blob/b984ff66f13d4d16a2ab4ee4f2c32f3edd304bd5/usecases/LDpred2/ldpred2.R#L129-L131
> 
> If I interpet this correct, since all are reversed in the map, those that are as expected in the sumstats get an inverted effect

Well spotted. I can test the effect of swapping the order of the list elements to see if this resolves the issue. 
I tested with the UKB Height GWAS sumstats @ofrei pointed to, and the resulting fit remained poor compared to PRSice:
![image](https://user-images.githubusercontent.com/2492641/219031598-ad9fa9b3-8415-4da3-8df1-fcb58ea03a69.png)

vs. 
![image](https://user-images.githubusercontent.com/2492641/219031774-11d59fbd-8e36-4ae7-91c1-a1d930ac7c5a.png)

**Comment by deepchocolate** [comment]
> > @espenhgn @ofrei I've found a problem.. I looked closer at the output of my test script and noted that there were a lot more reversed alleles than in the tutorial.
> > Looking at the tutorial the "map" object (corresponding to the .bim file) looks like this
> > ```
> > ##   ..$ chromosome  : int [1:45337] 1 1 1 1 1 1 1 1 1 1 ...
> > ##   ..$ marker.ID   : chr [1:45337] "rs3934834" "rs12726255" "rs11260549" "..
> > ##   ..$ genetic.dist: num [1:45337] 0.359 0.408 0.932 0.986 1.107 ...
> > ##   ..$ physical.pos: int [1:45337] 1005806 1049950 1121794 1162435 1314015..
> > ##   ..$ allele1     : chr [1:45337] "T" "G" "A" "A" ...
> > ##   ..$ allele2     : chr [1:45337] "C" "A" "G" "C" ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the tutorial they rename the columns like this (also removing one):
> > ```
> > map <- setNames(obj.bigSNP$map[-3], c("chr", "rsid", "pos", "a1", "a0"))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Meaning that allele1=a1 and allele2=a0 Looking at `ldpred2.R` this is performed at:
> > https://github.com/comorment/containers/blob/b984ff66f13d4d16a2ab4ee4f2c32f3edd304bd5/usecases/LDpred2/ldpred2.R#L129-L131
> > 
> > If I interpet this correct, since all are reversed in the map, those that are as expected in the sumstats get an inverted effect
> 
> Well spotted. I can test the effect of swapping the order of the list elements to see if this resolves the issue. I tested with the UKB Height GWAS sumstats @ofrei pointed to, and the resulting fit remained poor compared to PRSice: ![image](https://user-images.githubusercontent.com/2492641/219031598-ad9fa9b3-8415-4da3-8df1-fcb58ea03a69.png)
> 
> vs. ![image](https://user-images.githubusercontent.com/2492641/219031774-11d59fbd-8e36-4ae7-91c1-a1d930ac7c5a.png)
> 
> However, I will also double check the LDpred2 parameters I've set. The SUMSTATSv3 spec renames certain columns.

It's not just this one:
https://github.com/comorment/containers/blob/b984ff66f13d4d16a2ab4ee4f2c32f3edd304bd5/usecases/LDpred2/ldpred2.R#L129-L131

but also here:
https://github.com/comorment/containers/blob/b984ff66f13d4d16a2ab4ee4f2c32f3edd304bd5/usecases/LDpred2/ldpred2.R#L106

**Comment by espenhgn** [comment]
@deepchocolate, may I ask: Do you now run LDpred2 with our containers (`r.sif`) or just a normal installation in R/Rstudio? 
Can't rule yet rule out that the odd behavior I see is due to the versions of bigsnpr/bigreadr I've installed in the `r.sif` containers (defined in https://github.com/comorment/containers/blob/main/src/scripts/R/cran.R). Something may have gone wrong if the LDpred2 scripts were based on the tutorial from some other version. Merely speculation though. My testing with UKB sumstats files is still inconclusive for LDpred2-inf. The job timed out after 12h.

**Comment by deepchocolate** [comment]
> @deepchocolate, may I ask: Do you now run LDpred2 with our containers (`r.sif`) or just a normal installation in R/Rstudio? Can't rule yet rule out that the odd behavior I see is due to the versions of bigsnpr/bigreadr I've installed in the `r.sif` containers (defined in https://github.com/comorment/containers/blob/main/src/scripts/R/cran.R). Something may have gone wrong if the LDpred2 scripts were based on the tutorial from some other version. Merely speculation though. My testing with UKB sumstats files is still inconclusive for LDpred2-inf. The job timed out after 12h. I fixed the reordering of a1/a0 locally.

I only run them within the containers, except when I'm adding somthing not yet available in the container. There's some files I use that I keep separate (external LD files) in my development environment as I have not cloned those repos.

**Comment by espenhgn** [comment]
hi @deepchocolate. I think I found another problem in the `ldpred2.R` script, which was not of your doing of course as it is also present in the [tutorial](https://privefl.github.io/bigsnpr/articles/LDpred2.html#ldpred2-inf-infinitesimal-model). On this line https://github.com/comorment/containers/blob/b984ff66f13d4d16a2ab4ee4f2c32f3edd304bd5/usecases/LDpred2/ldpred2.R#L232 
the parameters `beta` and `beta_se` is parsed, however `beta` is a built-in function in R, and `beta_se` is not defined at all. 
Why the hell this doesn't cause the script to crash I do not know, but surely this line should be 
`ldsc <- with(df_beta, snp_ldsc(ld, ld_size, chi2=(df_beta$beta/df_beta$beta_se)^2, sample_size=n_eff, blocks=NULL))`?

**Comment by deepchocolate** [comment]
> hi @deepchocolate. I think I found another problem in the `ldpred2.R` script, which was not of your doing of course as it is also present in the [tutorial](https://privefl.github.io/bigsnpr/articles/LDpred2.html#ldpred2-inf-infinitesimal-model). On this line
> 
> https://github.com/comorment/containers/blob/b984ff66f13d4d16a2ab4ee4f2c32f3edd304bd5/usecases/LDpred2/ldpred2.R#L232
> 
> 
> the parameters `beta` and `beta_se` is parsed, however `beta` is a built-in function in R, and `beta_se` is not defined at all.
> Why the hell this doesn't cause the script to crash I do not know, but surely this line should be
> `ldsc <- with(df_beta, snp_ldsc(ld, ld_size, chi2=(df_beta$beta/df_beta$beta_se)^2, sample_size=n_eff, blocks=NULL))`?

Not sure it's a problem though, R is a bit funny. 
```
beta # shows beta () function body
beta <- 1
beta + 1  # 2
beta(1,2)  # return from beta()
```
I assume when using `with(data.frame, ...)` R looks in the data.frame environment first before looking at the global.

**Comment by espenhgn** [comment]
> Not sure it's a problem though, R is a bit funny.

R's sense of humor doesn't align at all with mine :-P

**Comment by deepchocolate** [comment]
> > Not sure it's a problem though, R is a bit funny.
> 
> R's sense of humor doesn't align at all with mine :-P

Mine neither, it's quite easy to go wrong when you wrap some code in a function and you forget a variable you defined in the global environment that you keep using inside the function.

**Comment by espenhgn** [comment]
Messed around some more with sumstats files from UKB (, and unfortunately I have not been able to produce sensible results using LDpred2 (as above, fixing the a1 a0 column reordering in the fix-17 branch). 

Commands (w. `/SUMSTATS/v3.1/STD_GRCh37/GIANT_HEIGHT_2018_UKB.sumstats.gz`):
```
export ROOT_DIR=/
export COMORMENT=/ess/p697/data/durable/users/espehage//comorment
export SIF=//ess/p697/data/durable/users/espehage/comorment/containers-fix-17/singularity
export LDPRED2_REF=//ess/p697/data/durable/users/espehage/comorment/ldpred2_ref
export MOBA=//ess/p697/cluster/users/ofrei/2022_moba_height_traj
export SUMSTATS=//cluster/projects/p697/projects/SUMSTATv3
export SINGULARITY_BIND=//ess/p697/data/durable/users/espehage/comorment/ldpred2_ref:/ldpred2_ref,//ess/p697/cluster/users/ofrei/2022_moba_height_traj:/MOBA,//cluster/projects/p697/projects/SUMSTATv3:/SUMSTATS
export RSCRIPT=singularity exec --home=/ess/p697/data/durable/users/espehage/comorment/containers-fix-17/pgs:/home --cleanenv //ess/p697/data/durable/users/espehage/comorment/containers-fix-17/singularity/r.sif Rscript
export PLINK=singularity exec --home=/ess/p697/data/durable/users/espehage/comorment/containers-fix-17/pgs:/home //ess/p697/data/durable/users/espehage/comorment/containers-fix-17/singularity/gwas.sif plink
export PRSICE=singularity exec --home=/ess/p697/data/durable/users/espehage/comorment/containers-fix-17/pgs:/home --cleanenv //ess/p697/data/durable/users/espehage/comorment/containers-fix-17/singularity/gwas.sif PRSice_linux
export PYTHON=singularity exec --home=/ess/p697/data/durable/users/espehage/comorment/containers-fix-17/pgs:/home --cleanenv //ess/p697/data/durable/users/espehage/comorment/containers-fix-17/singularity/python3.sif python3$RSCRIPT Rscripts/generate_eigenvec.R --pheno-file /MOBA/master_file.csv --eigenvec-file output/PGS_GIANT_LDpred2_auto/master_file.eigenvec --pca 6

$RSCRIPT Rscripts/extract_columns.R --input-file /MOBA/master_file.csv --columns FID IID SEX --output-file output/PGS_GIANT_LDpred2_auto/master_file.cov --header T

$RSCRIPT Rscripts/createBackingFile.R /MOBA/MoBaPsychGen_v1-500kSNPs-child.bed output/PGS_GIANT_LDpred2_auto/MoBaPsychGen_v1-500kSNPs-child.rds

$RSCRIPT Rscripts/ldpred2.R --ldpred-mode auto --file-pheno /MOBA/master_file.csv --geno-file output/PGS_GIANT_LDpred2_auto/MoBaPsychGen_v1-500kSNPs-child.rds --sumstats /SUMSTATS/v3.1/STD_GRCh37/GIANT_HEIGHT_2018_UKB.sumstats.gz --out output/PGS_GIANT_LDpred2_auto/test.score  --cores 16 --col-pheno height_8y_rint --col-chr CHR --col-snp-id RSID --col-A1 EffectAllele --col-A2 OtherAllele --col-bp POS --col-stat Z --col-stat-se SE --col-pvalue P --col-n N --stat-type BETA

$RSCRIPT Rscripts/evaluate_model.R --pheno-file /MOBA/master_file.csv --phenotype height_8y_rint --phenotype-class CONTINUOUS --score-file output/PGS_GIANT_LDpred2_auto/test.score --nPCs 6 --eigenvec-file output/PGS_GIANT_LDpred2_auto/master_file.eigenvec --covariate-file output/PGS_GIANT_LDpred2_auto/master_file.cov --out output/PGS_GIANT_LDpred2_auto/test_summary
``` 
Stdout: 
[run_GIANT_LDpred2_auto.txt](https://github.com/comorment/containers/files/10790886/run_GIANT_LDpred2_auto.txt)

**Comment by deepchocolate** [comment]
@espenhgn That LD-score regression looks wild:
```
### Running LD score regression
Results: Intercept = 1.196007 H2 = 309705.6 
```

**Comment by deepchocolate** [comment]
I have looked at Swedish and Estonian results now
Both match approximately 10 percent of the SNPs that I match running in MoBa (~1.2M)
While the Swedish LDSC looked pretty sensible, the Estonian does not
```
### Running LD score regression
Results: Intercept = 5.018455 H2 = 0.8602077 
```
I have tested changes in #131 in MoBa now, so I'll try to wrap that PR up and hopefully some issues are resolved

**Comment by deepchocolate** [comment]
> 

@espenhgn Had another look.. Did you try with option `--merge-by-rsid`?

**Comment by espenhgn** [comment]
> @espenhgn Had another look.. Did you try with option `--merge-by-rsid`? Couldn't see it in the most recent command you posted.

Will test this option.

**Comment by ofrei** [comment]
One potential issue could be if inconsistent choice of reference alleles in sumstats, LD file and genotype file isn't resolved correctly. To cover this with unit test it's possible to start with these scripts:
https://github.com/comorment/containers/blob/main/usecases/LDpred2/ldpred2_simulations.ipynb
and introduce random choice of reference alleles for genotype file (used for PRS computation), but also for the geno file used to perform GWAS . This can be done with plink:
```plink --bfile <> --a1-allele <> --make-bed --out <>```
just an idea...

**Comment by espenhgn** [comment]
Hmm, might finally be on to something. Dropped the `--file-pheno` and `--col-pheno` args to `ldpred2.R`, which produced
![image](https://user-images.githubusercontent.com/2492641/221908018-7bfeab88-b08c-46c5-8e71-bdcc4225d6fb.png)
from
![image](https://user-images.githubusercontent.com/2492641/221908244-5d86a6b7-8d55-449e-ac86-b6c8930f835f.png)

**Comment by deepchocolate** [comment]
@espenhgn Could it be something with:
https://github.com/comorment/containers/blob/b984ff66f13d4d16a2ab4ee4f2c32f3edd304bd5/usecases/LDpred2/ldpred2.R#L115-L119

Unless I missed something, the col-pheno/phile-pheno arguments shouldn't affect the scoring. But if you include the phenotype from input to output it could be some problem there

**Comment by espenhgn** [comment]
Did some testing of the `sort=T/F` argument to the line `merge(obj.bigSNP$fam, dataPheno, ...)` in case `--pheno-file` arg is used. Unfortunately, disabling sorting doesn't resolve the issue as I first thought, here showing the corresponding scores vs. each other:
<img width="803" alt="image" src="https://user-images.githubusercontent.com/2492641/222211898-f804eb7b-08a5-4d64-9dba-c77d669d03c8.png">

Seems like the way to get this work is not providing `--pheno-file` and `--col-pheno` in this case, which appears to me as strange. I opened #142, but this is a non-fix (at the moment).

**Comment by espenhgn** [comment]
> @espenhgn Yea, that's strange, but good that you identified where the problem is! I'll take a look tomorrow aswell

Thanks. Here are the files I used to create that plot: 
[issue-124.zip](https://github.com/comorment/containers/files/10869447/issue-124.zip)

**Comment by deepchocolate** [comment]
@espenhgn @ofrei I think the whole thing with dealing with phenotypes in `ldpred2.R` can be dropped. Unless I miss something it is only used to calculate a phenotypic correlation if it is provided. I think it also may confuse users that is something you should provide as if it would play a role in the calculation of the score (which it does not). The phenotype was used in the LDpred2 grid model to validate against, but we haven't implemented that, and the auto model is recommended by the LDpred2 creators.

Providing the phenotype does provide some convenience in the sense that you can get an output-file that contains the phenotype and the score together so your can do some basic analysis. But as I suggest in issue #144, the same behavior can be achieved by letting the user specify a file to merge the scores with. And if in some future development a phenotype is needed such a file could be declared mandatory.

**Comment by espenhgn** [comment]
I'm fine with removing this feature, especially as it creates problems such as those reported here.

**Comment by espenhgn** [comment]
Hi @deepchocolate. Discussed briefly w. @ofrei; he's ok with removing the ``--pheno-file`` arg stuff. It's probably better to do the model-performance evaluation in post anyway. But how shall we proceed? Shall I assign myself or do you want to take a look?

**Comment by deepchocolate** [comment]
> Hi @deepchocolate. Discussed briefly w. @ofrei; he's ok with removing the `--pheno-file` arg stuff. It's probably better to do the model-performance evaluation in post anyway. But how shall we proceed? Shall I assign myself or do you want to take a look?

If you wish, maybe you can remove them in your existing pull request #142 ?
